# Site settings
baseURL = "https://kokuzawa.github.io/"
languageCode = "ja-jp"
title = "KATSUMI KOKUZAWA'S BLOG"
theme = "angels-ladder"
disqusShortname = "katsumikokuzawasblog"

[Params]
copyright = "Written by Katsumi Kokuzawa"
twitter = "https://twitter.com/kokuzawa"
github = "https://github.com/kokuzawa"
showsRSS = true
analytics = "UA-36546771-1"
profile = "/images/avatar.png"

[taxonomies]
tag = "tags"

