# Site settings
baseURL = "https://kokuzawa.github.io/"
canonifyurls = true
languageCode = "ja-jp"
title = "Katsumi Kokuzawa's Blog"
theme = "hugo-cactus-theme"
disqusShortname = "Katsumii"
googleAnalytics = "UA-36546771-1"

[params]
name = "Katsumi Kokuzawa"
bio = "Programmer"
twitter = "kokuzawa"
socialIconStyle = "circle"

[social]
github = "https://github.com/kokuzawa"
twitter = "https://www.twitter.com/kokuzawa"
