---
title: "[買い物] Thule Crossover 25L BackPack TCBP-317 Black"
date: 2018-11-21T23:00:42+09:00
tags: [買い物]
draft: false
---

Thule Crossover 25L BackPack TCBP-317 Black を買った。これ。

++++
<a target="_blank"  href="https://www.amazon.co.jp/gp/product/B00J082KK6/ref=as_li_tl?ie=UTF8&camp=247&creative=1211&creativeASIN=B00J082KK6&linkCode=as2&tag=moonwhaleblog-22&linkId=9152d88bacbec1640b01cb7fb6949718"><img border="0" src="//ws-fe.amazon-adsystem.com/widgets/q?_encoding=UTF8&MarketPlace=JP&ASIN=B00J082KK6&ServiceVersion=20070822&ID=AsinImage&WS=1&Format=_SL250_&tag=moonwhaleblog-22" ></a><img src="//ir-jp.amazon-adsystem.com/e/ir?t=moonwhaleblog-22&l=am2&o=9&a=B00J082KK6" width="1" height="1" border="0" alt="" style="border:none !important; margin:0px !important;" />
++++

== 購入理由

最近ずっとブリーフケースで仕事行っていました。
まあ、中にそれほど物を入れる訳でも無いので、これで事足りていたというのもあるんですが。
実のところ、内容物云々の話よりも帰宅時にスーパーでお買い物をする際の問題という方が大きくて、
ブリーフケースと買い物カゴを持つと、商品を取り辛いんです。
で、最悪なのは雨が降った時で、傘とブリーフケースと買い物カゴを持って会計しようとすると、
財布が出せない。ここのところ天気もあまり良くなく、その三点セットで買い物することが多くなり、
これはやってられないと思い、ついにバックパックを購入することにしました。

== 選択理由

もっとビジネスちっくなのを最初は考えていたんですが、
スーツで仕事に行く訳でも無いので、ちょっとカジュアル寄りにして、
さらにはPCやコードやらがバラバラにならずに運べるものを探していました。
ハイキング用のリュックも持っているのですが、あれは中にポケットがほとんどないのです。
また、ポケットがなくてもバラバラにならないように、カバンに入れる仕分けケースのような物も持っているのですが、
結局出し入れが不便で使わなくなってしまうので、ポケットのある物が必須でした。

スーツ着て仕事に行くことがあるかも...とちょっと考えたんですが、
鞄を買うときにいつもそんなことを思って１０年、一度たりとてスーツを着ていないので、
着る可能性は考慮しないことに。

== という訳で

明日から背負っていきます。
メリットやデメリットはまだ使ってないのでわからないのですが、
１点だけ気になった部分があります。
公式の動画や色々な方のレビュー動画を見ていると、ネット状のポケットにiPhoneの充電ケーブルを入れているんですが、
コンセントの爪って結構鋭いじゃない？これネット部分に穴空きそうで怖いんですけど。
いや、人柱にはなりませんよ？怖いんで百均の透明なジッパー付きの袋に入れてからネットポケットに入れました。

